#!/usr/bin/python

import sys

def bubble_sort(num_array):
	for k in range(len(num_array)-1):
		for count,i in enumerate(reversed(num_array),1):
			if len(num_array)- count - 1 >= 0:
				if i < num_array[len(num_array)- count - 1]:
					num_array[len(num_array)- count], num_array[len(num_array)- count - 1] = num_array[len(num_array)- count - 1], num_array[len(num_array)- count]
	print num_array


if __name__=='__main__':
	print "Bubble Sorting\n"

	num_array = []
	num_of_elements = int(input("Enter number of elements you want to sort"))
	print "Enter your numbers below\n"

	if num_of_elements > 0:
		for count in range(num_of_elements):
			temp = 0
			temp = raw_input()
			num_array.append(int(temp))
		bubble_sort(num_array)
	else:
		print "Number of Elements cannot be 0 or less"
		sys.exit(1)
		
