#!/usr/bin/python

import os
import sys
import re
from pymongo import MongoClient

def convert2unicode(mydict):
	for k, v in mydict.iteritems():
		if isinstance(v, str):
			mydict[k] = unicode(v, errors = 'replace')
		elif isinstance(v, dict):
			convert2unicode(v)
